name: Generate CS2 EXE v4

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # v3 yerine v4 kullanıldı

    - name: Set up Python
      uses: actions/setup-python@v5 # v4/v3 yerine v5 kullanıldı
      with:
        python-version: "3.10"

    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install pymem pygame keyboard pywin32 pyinstaller

    - name: Build EXE with PyInstaller
        # --uac-admin: EXE'nin yönetici izni istemesini sağlar
      run: |
        pyinstaller --onefile --noconsole --uac-admin main.py

    - name: Upload Finished EXE
      uses: actions/upload-artifact@v4 # v3 yerine v4 kullanıldı
      with:
        name: CS2-External-Build
        path: dist/main.exe
        
